### ISSUE TITLE
Fails to build against mutter 3.32

### ISSUE THREAD

**Issue by Tireg** [elementary/greeter#379]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
When building greeter with Mutter 3.32, the build fails with this error:
```
compositor/fb12c4d@@io.elementary.greeter-compositor@exe/SystemBackground.c:57:22: error: field has incomplete type 'MetaBackgroundActor' (aka 'struct _MetaBackgroundActor')
        MetaBackgroundActor parent_instance;
                            ^
/usr/include/mutter-4/meta/meta-background-actor.h:40:1: note: forward declaration of 'struct _MetaBackgroundActor'
G_DECLARE_FINAL_TYPE (MetaBackgroundActor,
^
/usr/include/glib-2.0/gobject/gtype.h:1400:18: note: expanded from macro 'G_DECLARE_FINAL_TYPE'
  typedef struct _##ModuleObjName ModuleObjName;                                                         \
                 ^
<scratch space>:109:1: note: expanded from here
_MetaBackgroundActor
^
1 error generated.
```

### To Reproduce
1. Build greeter against Mutter 3.32

### Expected behavior

Greeter should build fine

### Logs

```
[16/37] /usr/lib/llvm/8/bin/clang -Icompositor/fb12c4d@@io.elementary.greeter-compositor@exe -Icompositor -I../pantheon-greeter-9999/compositor -I. -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/lib64/libffi-3.3_rc0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/gee-0.8 -I/usr/include/mutter-4 -I/usr/include/mutter-4/clutter -I/usr/include/json-glib-1.0 -I/usr/include/mutter-4/cogl -I/usr/include/gsettings-desktop-schemas -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -w '-DGETTEXT_PACKAGE="io.elementary.greeter"' -B /usr/lib/llvm/8/binutils-bin -O2 -march=native -pthread -DCLUTTER_ENABLE_COMPOSITOR_API -DCLUTTER_ENABLE_EXPERIMENTAL_API -DCOGL_ENABLE_EXPERIMENTAL_API -DCOGL_ENABLE_EXPERIMENTAL_2_0_API -MD -MQ 'compositor/fb12c4d@@io.elementary.greeter-compositor@exe/meson-generated_SystemBackground.c.o' -MF 'compositor/fb12c4d@@io.elementary.greeter-compositor@exe/meson-generated_SystemBackground.c.o.d' -o 'compositor/fb12c4d@@io.elementary.greeter-compositor@exe/meson-generated_SystemBackground.c.o' -c 'compositor/fb12c4d@@io.elementary.greeter-compositor@exe/SystemBackground.c'
FAILED: compositor/fb12c4d@@io.elementary.greeter-compositor@exe/meson-generated_SystemBackground.c.o 
/usr/lib/llvm/8/bin/clang -Icompositor/fb12c4d@@io.elementary.greeter-compositor@exe -Icompositor -I../pantheon-greeter-9999/compositor -I. -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/lib64/libffi-3.3_rc0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/gee-0.8 -I/usr/include/mutter-4 -I/usr/include/mutter-4/clutter -I/usr/include/json-glib-1.0 -I/usr/include/mutter-4/cogl -I/usr/include/gsettings-desktop-schemas -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -w '-DGETTEXT_PACKAGE="io.elementary.greeter"' -B /usr/lib/llvm/8/binutils-bin -O2 -march=native -pthread -DCLUTTER_ENABLE_COMPOSITOR_API -DCLUTTER_ENABLE_EXPERIMENTAL_API -DCOGL_ENABLE_EXPERIMENTAL_API -DCOGL_ENABLE_EXPERIMENTAL_2_0_API -MD -MQ 'compositor/fb12c4d@@io.elementary.greeter-compositor@exe/meson-generated_SystemBackground.c.o' -MF 'compositor/fb12c4d@@io.elementary.greeter-compositor@exe/meson-generated_SystemBackground.c.o.d' -o 'compositor/fb12c4d@@io.elementary.greeter-compositor@exe/meson-generated_SystemBackground.c.o' -c 'compositor/fb12c4d@@io.elementary.greeter-compositor@exe/SystemBackground.c'
compositor/fb12c4d@@io.elementary.greeter-compositor@exe/SystemBackground.c:57:22: error: field has incomplete type 'MetaBackgroundActor' (aka 'struct _MetaBackgroundActor')
        MetaBackgroundActor parent_instance;
                            ^
/usr/include/mutter-4/meta/meta-background-actor.h:40:1: note: forward declaration of 'struct _MetaBackgroundActor'
G_DECLARE_FINAL_TYPE (MetaBackgroundActor,
^
/usr/include/glib-2.0/gobject/gtype.h:1400:18: note: expanded from macro 'G_DECLARE_FINAL_TYPE'
  typedef struct _##ModuleObjName ModuleObjName;                                                         \
                 ^
<scratch space>:109:1: note: expanded from here
_MetaBackgroundActor
^
1 error generated.
```

## Platform Information

OS: Gentoo
Mutter: 3.32.2

- [X] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

## Additional context

This is exactly the same error as https://github.com/elementary/gala/pull/635#commitcomment-35869325.

The MetaBackgroundActor class changes for MUTTER334 (of this PR: https://github.com/elementary/greeter/pull/377) should be also applied for MUTTER332.

Greeter still builds fine with Mutter 3.30 and Mutter 3.34.
